project:
  type: book
  output-dir: docs


book:
  title: "Disciplina Programação II - Prof Gustavo"
  author: "Mário Diego Rocha Valente"
  date: "22/08/2024"
  chapters:
    - index.qmd
    - intro.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

