
```{=html}
<style>
  body{text-align: justify}
</style>
```


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

# Lista de Exercício {.unnumbered}


**Questão 1**: Conceito de Encapsulamento e Information Hiding
Explique o conceito de encapsulamento e como ele está relacionado ao princípio de Information Hiding. Por que é importante utilizar esses conceitos em projetos de software?

**Questão 2**: Visibilidade de Atributos e Métodos
Em Java, existem diferentes modificadores de visibilidade para atributos e métodos. Quais são esses modificadores, e qual o propósito de cada um deles? Dê exemplos de situações em que cada um deles seria mais adequado.

**Questão 3**: Separação de Responsabilidades
O princípio da separação de responsabilidades (Separation of Concerns) é essencial em Orientação a Objetos. Explique esse princípio e discuta como ele pode ser aplicado ao projetar classes e métodos em um sistema Java.

**Questão 4**: Implementação Prática - Classe "Livro" 
Implemente uma classe Livro em Java com os seguintes atributos: titulo (título do livro), autor (nome do autor), e numeroPaginas (número de páginas).
Todos os atributos devem ser privados.
A classe deve possuir construtores para inicializar os objetos e métodos para exibir as informações do livro (exibirDetalhes).
Implemente também os métodos getters e setters necessários.

**Questão 5**: Extensão Prática - Classe "Biblioteca" 
Com base na classe Livro criada na questão anterior, implemente uma classe Biblioteca que seja capaz de gerenciar múltiplos livros.
A classe Biblioteca deve possuir um atributo privado que armazene uma lista de livros.
Implemente métodos para adicionar novos livros, buscar um livro pelo título e exibir todos os livros disponíveis na biblioteca.
Considere o uso adequado de construtores, encapsulamento e visibilidade.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::